language: clojure
lein: lein2
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8
env:
  global:
    - PROJECT_DIR=${TRAVIS_BUILD_DIR}
script: lein2 clean && lein2 test
matrix:
  fast_finish: true
  allow_failures:
    - jdk: oraclejdk8
deploy:
  provider: heroku
  app: embee
  on:
    branch: master
    jdk: openjdk7
  api_key:
    secure: Z7+uaQ/2cVTb7C4EFkZUuulkJFCZI1JucO4nidZW4GYHKPX7hHkngtEuUmBS0z9SHikMvPEPbBjDzHl8Gh+diS0k+osyTf0CNepgV5mAarhR2amgLv8E60/43NZTvIeojNFx8Rs3OxRHULNrAXwHRLDw5Bs3lLg2zp2e/vTEYbo=
