language: clojure

lein: lein2

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8

env:
  global:
    - PROJECT_DIR=${TRAVIS_BUILD_DIR}
#    - PATH=${PROJECT_DIR}/bin:${PATH}
#    - _JAVA_OPTIONS='-Xms64m -Xmx128m -XX:+AggressiveOpts'

#install : ./travis/install.sh
script  : lein2 clean && lein2 test

matrix:
  fast_finish: true
  allow_failures:
    - jdk: oraclejdk8
